// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/**
 * Primary content in HeroImage → Primary
 *
 */
interface HeroImageSliceDefaultPrimary {
  /**
   * Image field in *HeroImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Default variation for HeroImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroImageSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<HeroImageSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HeroImage*
 *
 */
type HeroImageSliceVariation = HeroImageSliceDefault;
/**
 * HeroImage Shared Slice
 *
 * - **API ID**: `hero_image`
 * - **Description**: `HeroImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroImageSlice = prismicT.SharedSlice<
  "hero_image",
  HeroImageSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client;
  }
  namespace Content {
    export type {
      HeroImageSliceDefaultPrimary,
      HeroImageSliceDefault,
      HeroImageSliceVariation,
      HeroImageSlice,
    };
  }
}
